version: "3.8"

services:
  web:
    build:
      context: .
    container_name: careon-web
    env_file: .env
    command: daphne -b 0.0.0.0 -p 8000 careon.asgi:application
    volumes:
      - .:/app
      - static_volume:/app/static
    expose:
      - "8000"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: careon-redis
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    container_name: careon-nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/app/static

volumes:
  static_volume:
