# Generated by Django 5.2.7 on 2025-11-12 01:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("room", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_metrics",
                        to="room.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("memo", models.TextField(blank=True, null=True)),
                ("time_only", models.TimeField()),
                (
                    "date_only",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="care_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_logs",
                        to="room.room",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="log.logmetric",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="logmetric",
            index=models.Index(fields=["room"], name="log_logmetr_room_id_803af7_idx"),
        ),
        migrations.AddConstraint(
            model_name="logmetric",
            constraint=models.UniqueConstraint(
                fields=("room", "label"), name="uq_logmetric_room_label"
            ),
        ),
        migrations.AddIndex(
            model_name="carelog",
            index=models.Index(fields=["room"], name="log_carelog_room_id_69ef0c_idx"),
        ),
        migrations.AddIndex(
            model_name="carelog",
            index=models.Index(
                fields=["metric"], name="log_carelog_metric__bbe15e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carelog",
            index=models.Index(
                fields=["author"], name="log_carelog_author__1abdd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carelog",
            index=models.Index(
                fields=["room", "metric", "date_only", "time_only"],
                name="log_carelog_room_id_bfff75_idx",
            ),
        ),
    ]
