name: 🐛 Bug Report
description: 버그 또는 오류를 신고합니다.
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ 버그를 상세히 작성해주세요. 재현 가능한 단계와 기대 동작을 함께 적어주세요.
  - type: input
    id: summary
    attributes:
      label: 버그 요약
      description: 어떤 문제가 발생했나요?
      placeholder: 로그인 시 JWT 만료 오류 발생
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 재현 방법
      description: 문제를 재현하기 위한 단계를 작성해주세요.
      placeholder: |
        1. 로그인 시도
        2. 토큰 발급 요청
        3. 401 에러 발생
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 기대 동작
      description: 어떤 결과가 나와야 하나요?
      placeholder: 토큰이 정상적으로 재발급되어야 함
  - type: input
    id: environment
    attributes:
      label: 환경 정보
      description: OS, Python 버전 등 환경을 작성해주세요.
      placeholder: macOS / Python 3.10 / Django 5.0
