# Generated by Django 5.2.7 on 2025-11-08 13:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("room", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("finalized", "Finalized")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="room.room",
                    ),
                ),
            ],
            options={
                "db_table": "schedules",
            },
        ),
        migrations.CreateModel(
            name="ScheduleAvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                (
                    "hour",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ]
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="schedule.schedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "schedule_availability_slots",
            },
        ),
        migrations.CreateModel(
            name="ScheduleAvailabilitySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_submissions",
                        to="schedule.schedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "schedule_availability_submissions",
            },
        ),
        migrations.CreateModel(
            name="ScheduleConfirmedAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                (
                    "hour",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ]
                    ),
                ),
                ("finalized_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finalized_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmed_assignments",
                        to="schedule.schedule",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_confirmed_assignments",
            },
        ),
        migrations.CreateModel(
            name="ScheduleNeededSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                (
                    "hour",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ]
                    ),
                ),
                ("needed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="needed_slots",
                        to="schedule.schedule",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_needed_slots",
            },
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("room", "start_date"), name="uq_schedule_room_start_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="chk_sched_start_lte_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleavailabilityslot",
            constraint=models.UniqueConstraint(
                fields=("schedule", "user", "day", "hour"),
                name="uq_avail_schedule_user_day_hour",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleavailabilityslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("day__gte", 0), ("day__lte", 6)),
                name="chk_avail_day_0_6",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleavailabilityslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("hour__gte", 0), ("hour__lte", 23)),
                name="chk_avail_hour_0_23",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleavailabilitysubmission",
            constraint=models.UniqueConstraint(
                fields=("schedule", "user"), name="uq_submission_schedule_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleconfirmedassignment",
            constraint=models.UniqueConstraint(
                fields=("schedule", "day", "hour"),
                name="uq_confirmed_schedule_day_hour",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleconfirmedassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("day__gte", 0), ("day__lte", 6)),
                name="chk_confirm_day_0_6",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleconfirmedassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("hour__gte", 0), ("hour__lte", 23)),
                name="chk_confirm_hour_0_23",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleneededslot",
            constraint=models.UniqueConstraint(
                fields=("schedule", "day", "hour"), name="uq_needed_schedule_day_hour"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleneededslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("day__gte", 0), ("day__lte", 6)),
                name="chk_need_day_0_6",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleneededslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("hour__gte", 0), ("hour__lte", 23)),
                name="chk_need_hour_0_23",
            ),
        ),
    ]
