# Generated by Django 5.2.7 on 2025-11-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("room", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeekSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("is_finalized", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_schedules",
                        to="room.room",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start"],
                "unique_together": {("room", "week_start")},
            },
        ),
    ]
