# Generated by Django 5.2.7 on 2025-11-05 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NeededCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.SmallIntegerField()),
                ("hour", models.SmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="needed_cells",
                        to="schedule.weekschedule",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["week", "day", "hour"],
                        name="schedule_ne_week_id_5d85e8_idx",
                    )
                ],
                "unique_together": {("week", "day", "hour")},
            },
        ),
    ]
