# Generated by Django 5.2.7 on 2025-11-23 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("room", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="캘린더에서 선택된 기준 날짜")),
                ("title", models.CharField(max_length=255)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("is_all_day", models.BooleanField(default=False)),
                (
                    "repeat_rule",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("repeat_until", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="설명(50자 이내)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="room.room",
                    ),
                ),
            ],
            options={
                "ordering": ["start_at"],
            },
        ),
        migrations.CreateModel(
            name="CalendarAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("AUDIO", "Audio")], max_length=10
                    ),
                ),
                ("url", models.URLField(blank=True, default="", max_length=2048)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="calender.calendarevent",
                    ),
                ),
            ],
        ),
    ]
