# Generated by Django 5.2.7 on 2025-11-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calender", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "type",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("AUDIO", "Audio")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
