name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Web image (Daphne)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sebinbaek0918/careon-backend-web:latest

      - name: Build and push Nginx image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: sebinbaek0918/careon-backend-nginx:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/ubuntu/CAREON-BACKEND   # ✅ docker-compose.yml이 있는 경로로 이동

            echo "1️⃣ Pulling latest images..."
            sudo docker compose pull

            echo "2️⃣ Stopping old containers..."
            sudo docker compose down           # ✅ Redis 포함 새 네트워크 재구성 위해 down 추가

            echo "3️⃣ Running migrations..."
            sudo docker compose up -d web redis nginx certbot
            sudo docker compose exec web python manage.py migrate --noinput   # ✅ exec 사용

            echo "4️⃣ Restarting full stack..."
            sudo docker compose up -d

            echo "5️⃣ Cleaning up unused images..."
            sudo docker image prune -f

            echo "✅ Deployment completed successfully!"
